import React, {Component} from 'react';
import Blogs from '../Props/blogs';
import Blogsb from '../Props/blogsb';

class Props extends Component {
    render() { 
        return (  
            <div className="prowraper">
                <Blogs img={require('../images/slider1.jpg')} date="15 september 2019" heading="Kini indihome di sumedang" des="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non felis ex. In hac habitasse platea dictumst. Etiam aliquam non quam sed sodales. Sed vitae tristique erat, ac viverra nulla. Donec turpis nibh, vulputate ac purus in, consequat lobortis quam. Nam blandit libero sed leo faucibus lacinia. Maecenas in malesuada ipsum. Proin et ex eget est rhoncus suscipit. Etiam efficitur, odio sit amet varius sodales, sem nibh molestie ante, eget elementum odio lectus rutrum dolor. Mauris dapibus tortor erat, euismod efficitur odio dignissim at. Ut posuere risus nec metus convallis, nec ultrices mi venenatis. Sed diam magna, sollicitudin a tellus non, iaculis luctus velit. Donec pharetra libero at efficitur euismod."/>
                <Blogs img={require('../images/republika.jpg')} date="19 september 2019" heading="Kini indihome ada inovasi baru" des="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non felis ex. In hac habitasse platea dictumst. Etiam aliquam non quam sed sodales. Sed vitae tristique erat, ac viverra nulla. Donec turpis nibh, vulputate ac purus in, consequat lobortis quam. Nam blandit libero sed leo faucibus lacinia. Maecenas in malesuada ipsum. Proin et ex eget est rhoncus suscipit. Etiam efficitur, odio sit amet varius sodales, sem nibh molestie ante, eget elementum odio lectus rutrum dolor. Mauris dapibus tortor erat, euismod efficitur odio dignissim at. Ut posuere risus nec metus convallis, nec ultrices mi venenatis. Sed diam magna, sollicitudin a tellus non, iaculis luctus velit. Donec pharetra libero at efficitur euismod."/>

                {/*  */}
                <Blogsb img={require('../images/slider1.jpg')} date="12 september 2019" heading="Kini indihome ada inovasi baru" des="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non felis ex. In hac habitasse platea dictumst. Etiam aliquam non quam sed sodales. Sed vitae tristique erat, ac viverra nulla. Donec turpis nibh, vulputate ac purus in, consequat lobortis quam. Nam blandit libero sed leo faucibus lacinia. Maecenas in malesuada ipsum. Proin et ex eget est rhoncus suscipit. Etiam efficitur, odio sit amet varius sodales, sem nibh molestie ante, eget elementum odio lectus rutrum dolor. Mauris dapibus tortor erat, euismod efficitur odio dignissim at. Ut posuere risus nec metus convallis, nec ultrices mi venenatis. Sed diam magna, sollicitudin a tellus non, iaculis luctus velit. Donec pharetra libero at efficitur euismod."/>
                <Blogsb img={require('../images/bpn.jpg')} date="12 september 2019" heading="Kini indihome ada inovasi baru" des="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non felis ex. In hac habitasse platea dictumst. Etiam aliquam non quam sed sodales. Sed vitae tristique erat, ac viverra nulla. Donec turpis nibh, vulputate ac purus in, consequat lobortis quam. Nam blandit libero sed leo faucibus lacinia. Maecenas in malesuada ipsum. Proin et ex eget est rhoncus suscipit. Etiam efficitur, odio sit amet varius sodales, sem nibh molestie ante, eget elementum odio lectus rutrum dolor. Mauris dapibus tortor erat, euismod efficitur odio dignissim at. Ut posuere risus nec metus convallis, nec ultrices mi venenatis. Sed diam magna, sollicitudin a tellus non, iaculis luctus velit. Donec pharetra libero at efficitur euismod."/>
                <Blogsb img={require('../images/slider1.jpg')} date="12 september 2019" heading="Kini indihome ada inovasi baru" des="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non felis ex. In hac habitasse platea dictumst. Etiam aliquam non quam sed sodales. Sed vitae tristique erat, ac viverra nulla. Donec turpis nibh, vulputate ac purus in, consequat lobortis quam. Nam blandit libero sed leo faucibus lacinia. Maecenas in malesuada ipsum. Proin et ex eget est rhoncus suscipit. Etiam efficitur, odio sit amet varius sodales, sem nibh molestie ante, eget elementum odio lectus rutrum dolor. Mauris dapibus tortor erat, euismod efficitur odio dignissim at. Ut posuere risus nec metus convallis, nec ultrices mi venenatis. Sed diam magna, sollicitudin a tellus non, iaculis luctus velit. Donec pharetra libero at efficitur euismod."/>
                <Blogsb img={require('../images/slider1.jpg')} date="12 september 2019" heading="Kini indihome ada inovasi baru" des="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non felis ex. In hac habitasse platea dictumst. Etiam aliquam non quam sed sodales. Sed vitae tristique erat, ac viverra nulla. Donec turpis nibh, vulputate ac purus in, consequat lobortis quam. Nam blandit libero sed leo faucibus lacinia. Maecenas in malesuada ipsum. Proin et ex eget est rhoncus suscipit. Etiam efficitur, odio sit amet varius sodales, sem nibh molestie ante, eget elementum odio lectus rutrum dolor. Mauris dapibus tortor erat, euismod efficitur odio dignissim at. Ut posuere risus nec metus convallis, nec ultrices mi venenatis. Sed diam magna, sollicitudin a tellus non, iaculis luctus velit. Donec pharetra libero at efficitur euismod."/>
            </div>
        );
    }
}
 
export default Props;